### ISSUE TITLE
Can the message prompt title be customized?

### ISSUE THREAD

**Issue by sx212** [lsfusion/platform#1092]
![image](https://github.com/lsfusion/platform/assets/16461420/f75fb141-1c82-4bda-96ae-c79da55f30db)

**Comment by CrushBy** [comment]
Yes, it's possible. Could you ask this question on [StackOverflow](https://stackoverflow.com/questions/tagged/lsfusion) ? We will give a detailed answer there so that other developers can also see how to do it.

**Comment by ichavchavadze** [comment]
Now you can write
`MESSAGE 'ok' HEADER 'hello';`
