### ISSUE TITLE
Comments present in the interpreter's form are considered an error.

### ISSUE THREAD

**Issue by danchanka** [lsfusion/platform#1232]
![image](https://github.com/user-attachments/assets/15a919eb-dc73-48e8-9ca1-9639c3a18a29)

It seems the issue is with converting the grammar for the interpreter.

**Comment by pavel-miniutka** [comment]
Fixed in https://github.com/lsfusion/jenkins/commit/2ceb2ebd33f0bbb549f2780880de29029f7c26fb
