### ISSUE TITLE
Unable to reset a property value using the keyboard

### ISSUE THREAD

**Issue by CrushBy** [lsfusion/platform#1280]
If you press the DELETE key while in a field for which you can select from a list, the value itself is reset, but the first object in the list is selected. If you then press ENTER, it is the same object that will be substituted.

Thus, it is not possible to reset the value to null using the keyboard.

**Comment by alex-byi** [comment]
Already fixed in [90bb3c6](https://github.com/lsfusion/platform/commit/90bb3c69283de6d4f811b2298c32e55e95e647d4)
