### ISSUE TITLE
Wrong placement of controls on form in panel

### ISSUE THREAD

**Issue by PavelKirkouski** [lsfusion/platform#183]
Placement of controls change on every new edit form.

**Comment by danchanka** [comment]
![image (5)](https://user-images.githubusercontent.com/20270415/66033118-f1c08000-e506-11e9-957d-10959bbf9f37.png)
![image (6)](https://user-images.githubusercontent.com/20270415/66033123-f422da00-e506-11e9-81e8-1e0b2a8b02a2.png)
