### ISSUE TITLE
Can't close form when prevent changes to all properties enabled

### ISSUE THREAD

**Issue by flood6068** [lsfusion/platform#217]
If I set option "Prevent changes to all properties" for a role users under this role can't close any form.
![image.png](https://images.zenhubusercontent.com/5e1d95d6e924e35933b753fa/d45f4f20-2062-47ce-a34c-96d56969849a)
The reuslt is
![image.png](https://images.zenhubusercontent.com/5e1d95d6e924e35933b753fa/5029962c-2f4d-4272-9e6e-9a5c39e03609)
Could you please fix it

**Comment by ichavchavadze** [comment]
Security Policy was refactored, now this option doesn't exist.
https://docs.lsfusion.org/Security_policy/
