### ISSUE TITLE
It's possible to correct head of purchase invoice when prevent of objects changing is enabled

### ISSUE THREAD

**Issue by flood6068** [lsfusion/platform#218]
Is it correct behavior when I set to the role parameter "prevention of objects changing" enabled and can correct head of documents (f.e. purchase invoice), but can't correct table part of this document?
![image.png](https://images.zenhubusercontent.com/5e1d95d6e924e35933b753fa/c51c5fb8-0119-444e-b064-69bc12b2d960)

![image.png](https://images.zenhubusercontent.com/5e1d95d6e924e35933b753fa/4830fcef-53dc-47b8-8e0c-1230892136b7)

![image.png](https://images.zenhubusercontent.com/5e1d95d6e924e35933b753fa/d7e29f74-651a-4a32-bbf8-8d9dad50ac58)

**Comment by ichavchavadze** [comment]
Security Policy was refactored, now this option doesn't exist.
https://docs.lsfusion.org/Security_policy/
