### ISSUE TITLE
It's unclear how to allow or deny rights for role

### ISSUE THREAD

**Issue by flood6068** [lsfusion/platform#220]
![image.png](https://images.zenhubusercontent.com/5e1d95d6e924e35933b753fa/da9fa481-d81f-470c-b569-2fa0fc370399)

For my mind if I chose to deny all navigator elements in upper window there must be checked in lower window.
Could you refactor it, please.

**Comment by ichavchavadze** [comment]
The security policy has been significantly redesigned, you can view the current functionality here
https://docs.lsfusion.org/Security_policy/
