### ISSUE TITLE
Interrupt in busy dialog with useRequestTimeout = true doesn't interrupt main thread

### ISSUE THREAD

**Issue by Eveigh** [lsfusion/platform#289]
Also the problem is that retried call is shown in stack displayed to admin.
![image](https://user-images.githubusercontent.com/40161800/73157022-c0d90c00-40f0-11ea-9c29-1461c3157b11.png)

But the main problem is that SQL query is also not interrupted

**Comment by ichavchavadze** [comment]
Interrupt works without problems after this commit
https://github.com/lsfusion/platform/commit/2638a47d7318bccdbc993c819efc684e5db20c6a
