### ISSUE TITLE
Incorrect layouting in web-client with large texts

### ISSUE THREAD

**Issue by YraBos** [lsfusion/platform#291]
Приложение картотека. В WEB версии контролы (примечание, прочие) "наползают" друг на друга, в отличии от десктопной версии, где отображение выглядит нормально
![scr_bag](https://user-images.githubusercontent.com/60366596/73214314-fae2f600-4162-11ea-95d3-16e7b718588f.jpg)

**Comment by ichavchavadze** [comment]
Can't reproduce
