### ISSUE TITLE
Support dark theme versions for all icons on server

### ISSUE THREAD

**Issue by AlexKirkouski** [lsfusion/platform#294]
There two main paths with icons:
platform\web-client\src\main\java\lsfusion\gwt\public\static\images
platform\desktop-client\src\main\resources\images

Icons should be with the name: myicon_dark.png

**Comment by AlexKirkouski** [comment]
Also larger icon sizes (for example _32) would be great (to provide better UI scale support)

**Comment by ichavchavadze** [comment]
Already solved
