### ISSUE TITLE
Exception with min inflate ratio when exporting to xls

### ISSUE THREAD

**Issue by AlexKirkouski** [lsfusion/platform#297]
It seems that in zip library there is somewhy constraint on min inflate ration 0.01000

![image](https://user-images.githubusercontent.com/9713320/73342861-7b534500-4290-11ea-9ea7-
52075991bcef.png)

So the issue is to disable that constraint somehow

**Comment by ichavchavadze** [comment]
already solved
[(#0c170e89)](https://github.com/lsfusion/platform/commit/0c170e8974ebfefd64364e15c15d0bd6bc677190)
