### ISSUE TITLE
Как встроить график в интерфейс

### ISSUE THREAD

**Issue by MaximPetrichuk** [lsfusion/platform#303]
Добрый день!
Попытался зайти на ваш Slack (https://slack.lsfusion.org/) - но там выдает сообщение о битой ссылке, потому задаю вопрос здесь:

Подскажите пожалуйста, как я могу интегрировать графики в приложение, создаваемое на вашей платформе? 

Т.е. мне нужно отображать пользователю таблицу с данными и рядом график, визуализирующий эту таблицу.

С уважением, Максим.

**Comment by ichavchavadze** [comment]
With the help of custom components you can draw everything you want. 
https://docs.lsfusion.org/How-to_Custom_components_properties/

Also you can add grafs and charts with the help of pivot
https://docs.lsfusion.org/Pivot_block/
