### ISSUE TITLE
Implement more default + custom property renderer / editor

### ISSUE THREAD

**Issue by AlexKirkouski** [lsfusion/platform#441]
Now for every type there is a default renderer / editor (for text - textfield, for boolean - checkbox, for action - button , etc.). So the issue is to implement  extra renderers (for example for action instead of buttion use hyperlink, for boolean - button) + posibility for developer to use custom renderers just like for a list view #195.

**Comment by alex-byi** [comment]
Implements custom renderers and custom editors.
Now on form object declarations you can use custom javascript renderers and editors.
How-to:

**Comment by alex-byi** [comment]
Сhanged the syntax of declaration custom properties.
Now on form property declarations you can use following lsf-grammar:
CUSTOM [RENDER 'renderFunction'] [EDIT [TEXT / REPLACE] 'editFunctions'].
   #### **renderFunction** 
   renderFunction should be a javascript function without arguments that returns 3 functions with names and arguments like this  
   - **render(element)**
   - **update(element, controller, value)**
   - **clear(element)**
   Where 
      - element is com.google.gwt.dom.client.Element
      - value is JavaScriptObject
      - controller is JavaScriptObject with 4 functions:
        - changeValue(event, value). Void function. Event may be null.
        - isReadOnly(). Return true/false
        - toDateDTO(year, month, day). Convert js Date to GDateDTO. Return GDateDTO object. All params is int values.
        - toTimeDTO(hour, minute, second). Convert js Date to GTimeDTO. Return GTimeDTO object. All params is int values. 

   #### **editFunctions** 
   editFunctions should be a javascript function without arguments that returns:
   -  if TEXT option:
      - 2 functions with names and arguments like this
         - **render(element, editor)**
         - **clear(element)**
         Where
            - element is com.google.gwt.dom.client.Element
            - editor is JavaScriptObject with 1 function:
               - setDeferredCommitOnBlur(deferredCommitOnBlur). Void function. deferredCommitOnBlur is boolean value.
   -  if REPLACE option:
      - 5 functions with names and arguments like this
         - **render(element)**
         - **startEditing(element)**
         - **commit(element)**
         - **clearRender(element)**
         - **onBrowserEvent()**
         Where 
            - element is com.google.gwt.dom.client.Element
   - if only EDIT option:
      - 3 functions with names and arguments like this
         - **startEditing(element)**
         - **commit(element)**
         - **onBrowserEvent()**
         Where
            - element is com.google.gwt.dom.client.Element 

### How-to
   1. Just create javascript file with necessary functions.
   2. Put this file into server resources/web folder
   3. Set editor and / or render functions in form property declaration

Examples:
   #### Сommon case
   1. Create js file with content
```
function exampleFunction() {
    return {
        render: function (element) {
            //    do something
        },
        update: function (element, controller, value) {
            //    do something
        },
        clear: function (element) {
            //    do something
        }
    }
}
```
   2. Put file into resources/web
   3. Set custom render in form property declaration
```
FORM test
    OBJECTS a = Object
    PROPERTIES(a) value CUSTOM RENDER 'exampleFunction'
;  
```
#### Use predefined render / edit types
   - **Predefined input types. Just set custom input type in form property declaration**
      - 4 types are supported: range, month, date, time. Use with next syntax:
```
PROPERTIES() range PANEL CUSTOM RENDER 'customInputRange'
PROPERTIES() month PANEL CUSTOM RENDER 'customInputMonth'
PROPERTIES() date PANEL CUSTOM RENDER 'customInputDate'
PROPERTIES() time PANEL CUSTOM RENDER 'customInputTime'
```
   - **Also added support for google autocomplete**
      - To use google autocomplete no more need to create js files. 
      - Just set google api key in Administration -> Application -> Options -> Map provider table -> Google Api Key. 
      - Optional set Country code parameter in the same place.
      - After that just set custom render in form property declaration
```
PROPERTIES() autocomplete PANEL CUSTOM EDIT TEXT 'customGoogleAutocomplete'
```
