### ISSUE TITLE
Нет горизонтальной полосы прокрутки, если грид скрывается справа за экраном

### ISSUE THREAD

**Issue by flood6068** [lsfusion/platform#597]
![image](https://user-images.githubusercontent.com/19212251/114568240-a307b080-9c7c-11eb-8b99-bd9b4f26bd24.png)

Нет горизонтальной полосы прокрутки, если грид скрывается справа за экраном

**Comment by AFilipchyk** [comment]
Обычно в github'е мы создаём задачи на английском

**Comment by flood6068** [comment]
Но косячите то вы, ведь, на русском.

**Comment by CrushBy** [comment]
Это проблема дизайна конкретной формы (надо контейнер обернуть в SCROLLBAR). Вопрос к "конфигурации", а не платформе.
