### ISSUE TITLE
Support Google / Yandex / OSM maps tiles in map view

### ISSUE THREAD

**Issue by alex-byi** [lsfusion/platform#607]

**Comment by alex-byi** [comment]
By default Map-view uses OSM. 
To use google or yandex maps as tile you need to receive API key from google / yandex, store this key into Administration -> Application -> Options -> Map providers. And in FORM MAP declaration add 'google' or 'yandex' e.g.:

```
FORM map
    OBJECTS o = Element MAP 'google'
;
```

**Comment by ichavchavadze** [comment]
Also need to include module Geo.lsf, where map providers are declared.
