### ISSUE TITLE
Implement "custom html" container

### ISSUE THREAD

**Issue by AlexKirkouski** [lsfusion/platform#721]
Example:

```
NEW myCont {
     custom = "<div>[x]</div>"
     MOVE x {...}
}
```

**Comment by alex-byi** [comment]
Custom statement is string with html code / tags and square brackets with name of containers in it or only square brackets with name of containers in it. Elements can be placed in any order:
 - ``` custom = [containerName_1][containerName_2][containerName_N] ```
 - ``` custom = <div>[containerName_1]</p>[containerName_2][containerName_N]</div> ```

For example:
```
first = DATA STRING();
second = DATA INTERVAL[DATE]();
third = DATA BOOLEAN();

FORM form
    PROPERTIES() first, second, third;

DESIGN form {
    NEW firstContainer {
        MOVE PROPERTY(first());
        caption = first();
    }
    NEW secondContainer {
        MOVE PROPERTY(second()); 
    }
    NEW thirdContainer {
        MOVE PROPERTY(third()); 
    }
    custom = '<div style="background: yellow;color: red;font-weight: bolder;height: 100px;">[secondContainer]</p></p>[thirdContainer]</div><div style="opacity: .5">[firstContainer]</div>';
}
```
The output is the following:

![image](https://user-images.githubusercontent.com/38064030/159002167-b558a067-b011-4632-b84b-5fb2cf9826f3.png)
