### ISSUE TITLE
Fixed columns in grid

### ISSUE THREAD

**Issue by AlexKirkouski** [lsfusion/platform#75]
Like in excel - fixed columns remain at the same place, no matter of user scrolling.

**Comment by wolant87** [comment]
Our Clients send us very strоng requier for that feature. Thank you for collaboration.

**Comment by AlexKirkouski** [comment]
Should be done something like this http://fixedheadertable.com/

Create virtual table with absolute positioning and top left 0 then move all data from header and body for fixed columns to that virtual table (but keeping columns in original grid).

But all that should be done only when horizontal scroll is present / needed.

**Comment by AlexKirkouski** [comment]
Duplicate https://github.com/lsfusion/platform/issues/670
