### ISSUE TITLE
Filter improvements

### ISSUE THREAD

**Issue by CrushBy** [lsfusion/platform#832]
- **Ability for user to switch search from smart search to Contains**
- **Ability to insert a value from the keyboard buffer (CTRL+V) with the mouse**
- **Add % to the edges of Contains even if % is inside string**
- **When filtering for equality, the first value is automatically selected. It is not possible to enter an arbitrary value.**
- **Ability to globally change the delimiter from comma to another character**
- **Filter != by empty values should only show nonempty values**
- **Move + and X buttons up to the main filters**
- The previously set value should not be cleared when selecting a new value from the list with the separator.

**Comment by ichavchavadze** [comment]
Everything implemented
