### ISSUE TITLE
Implement user activity properties / events

### ISSUE THREAD

**Issue by AlexKirkouski** [lsfusion/platform#949]
For now, there should 3 types of such activities:

FILTER - changing filter
ORDER - changing order
FOCUS - changing focus

All this activities should be scoped to group objects for now (later it maybe also possible to scope such action / events to properties).

So syntax should be:

Event block:
ON [FILTER | ORDER | FOCUS] go [TO propertyNoParams]
Action:
[FILTER | ORDER | FOCUS] go [FROM propertyNoParams]

Property should store JSON (or CSV) string which should contain the data about the filter / order / focus.

For example (for order):

propA;true
propB;false

PS: Property action / event syntax could be the same, but property should contain more "granular data" (for example, for order, REPLACE, ADD, REMOVE, DIRECTION)/

**Comment by pavel-miniutka** [comment]
2 types of activities are implemented for the moment: ORDER and FILTER

Examples of actions:

`ORDERS|FILTERS form.obj [TO jsonProp];`
This will store current form.obj orders/filters info into jsonProp or default System.orders()/System.filters() property
`ORDER|FILTER form.obj [FROM jsonProp];`
This will read JSON orders/filters info from jsonProp or default System.orders()/System.filters() property and apply corresponding orders/filters to form.obj group object.

Form events block:
```
ON ORDER obj {
    ...
}
ON FILTER obj {
    ...
}
```

JSON structure:

For ORDER:
```
[{
    "property":<property_draw_SID>,
    "desc":true/false
}]
```
For FILTER:
```
[{
    "property":<property_draw_SID>,
    "compare":<=, >, <, >=, <=, !=, @, _, IN ARRAY>,
    "negation":true/false, 
    "value":<value>,
    "or":true/false
}]
```
"desc", "compare", "negation", "value" and "or" are optional keys

Also forms for quick import and modification of user activity info were added: SystemEvents.orders and SystemEvents.filters.
Here is the simple example of action which reverses current orders in grid:

```
reverseOrders() {
    ORDERS form.obj;
    IMPORT orders FROM orders();
    FOR property(INTEGER i) DO {
        desc(i) <- NOT desc(i);
    }
    EXPORT orders TO orders;
    ORDER form.obj;
}

```
