### ISSUE TITLE
boos 可以出中文版么？

### ISSUE THREAD

**Issue by menglinxi** [lsfusion/platform#952]
boos 可以出中文版么？

**Comment by danchanka** [comment]
Chinese has been added to the resource files in the master branch (commit: c7760ae). It's only machine-translated at the moment. The resource files are stored in ASCII. To view and edit them in a normal way, you can use the Resource Bundle Editor plugin in Intellij IDEA, for example. 
We would be grateful if you could help us improve the translation.

**Comment by ichavchavadze** [comment]
Chinese is already supported
